FROM node:18-bullseye-slim AS build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
RUN npm i -g @angular/cli
COPY package.json /app/package.json
RUN npm i -y
COPY . .
CMD ["node", "src/runScript.js"]
